sundayTen/agaein

agaein_web/src/App.tsx
agaein_web/src/Router/index.tsx
agaein_web/src/assets/styles/GlobalStyle.js

Set global style

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/article/index.ts
agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/resolvers/comment/index.ts
agaein_server/graphql/resolvers/comment/mutations.ts
agaein_server/graphql/resolvers/comment/queries.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/resolvers/user/queries.ts
agaein_server/graphql/typedefs/Article.graphql
agaein_server/graphql/typedefs/comment.graphql
agaein_server/graphql/typedefs/index.graphql
agaein_server/index.ts

코멘트와 게시물 생성 및 조회 기능 구현 완료(타이틀과 내용만)
데이터베이스 테이블 finding -> looking_for 로 변경
코멘트 테이블에 user_id 누락되어서 추가
ps. 현재 기능만 있으면 메인화면 구성하는데는 지장없을 것 같습니다. 이번 주 메인화면 구성에 좀 더 필요한 기능이 있으면 코멘트로 달아주세요.

comment & article CR 기능 구현

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/user/queries.ts
agaein_server/package.json
agaein_server/yarn.lock

해당 부분 고쳤습니다.
보니까 nullable의 문제가 아니라 DB상에 null데이터는 없었는데, snakecas와 camelcase가 연동이 안 되어서 생긴 문제였습니다. objection 라이브러리를 이용하여 해결하였고, created_at과 updated_at 둘 다 not nullable 처리 하였습니다.

fix: 🐛 생성, 수정시간 nullable 변경 & snakecase <-> camelcase 연동

---

agaein_web/dockerfile

web-dockerfile에 yarn codegen 추가
특이사항 없으므로 바로 머지하겠습니다.

web-dockerfile에 yarn codegen 추가

---

agaein_web/src/components/molecules/NavBar/index.tsx
agaein_web/src/components/molecules/NavBar/style.tsx
agaein_web/src/components/organism/kakaomap/KakaoMap.tsx

Navbar
- 로그인 시 UI 변경
KakaoMap
- 파라미터 type 지정

Update Navbar, KakaoMap

---

agaein_web/src/assets/styles/GlobalStyle.js
agaein_web/src/components/molecules/PostItemBox/PostItemBox.style.ts
agaein_web/src/components/molecules/PostItemBox/PostItemBox.tsx
agaein_web/src/components/pages/home/Home.tsx
agaein_web/src/components/templates/PostList/PostList.style.ts
agaein_web/src/components/templates/PostList/PostList.tsx
agaein_web/src/index.css

- index.css 로 reset css 옮기기
- post list component 추가

Add post list component

---

agaein_web/src/App.tsx
agaein_web/src/components/organism/AppLayout/AppLayout.style.ts
agaein_web/src/components/organism/AppLayout/AppLayout.tsx
agaein_web/src/components/templates/PostList/PostList.style.ts

Add AppLayout

---

Jenkinsfile

chore: 🤖 build order change

---

agaein_server/graphql/database.ts
agaein_server/index.ts

* 데이터 베이스 스키마 회의 내용대로 변경
* 예전 스키마 형태의 테이블이 살아있음. 백엔드 서버 변경완료 시, 알려주고 이전 스키마 및 DB 테이블 삭제 예정

데이터베이스 스키마 변경 및 적용

---

agaein_web/package.json
agaein_web/src/components/molecules/Modal/Modal.style.ts
agaein_web/src/components/molecules/Modal/index.tsx
agaein_web/src/components/organism/kakaomap/KakaoMap.tsx
agaein_web/src/components/organism/mapModal/MapModal.tsx
agaein_web/src/components/pages/createArticle/Step2.tsx
agaein_web/tsconfig.json
agaein_web/yarn.lock

Modal
- 팝업 구현
KakaoMap
- 연습 기능들 주석
- 클릭 위치에 마커 + 주소 표출 구현
? 차후 공통 컴포넌트로 수정할지 논의 필요
MapModal
- 클릭한 맵의 주소 전달 구현

Map Modal 초안, 캘린더 라이브러리 적용

---

agaein_web/src/components/pages/createArticle/Step1.tsx

- Step1 isButtonDisabled 함수 다시 추가
없음

Step1 isButtonDisabled 함수 다시 추가

---

agaein_server/graphql/resolvers/article/mutations.ts

뮤테이션 오브젝트 데이터 간소화
서버 정상화 확인용 풀리퀘스트

refactor: 💡 object data minimize

---

agaein_web/package.json
agaein_web/src/components/molecules/BookMark/BookMark.style.ts
agaein_web/src/components/molecules/BookMark/BookMark.tsx
agaein_web/src/components/molecules/BookMark/index.ts
agaein_web/src/components/molecules/Chip/Chip.style.ts
agaein_web/src/components/molecules/Chip/Chip.tsx
agaein_web/src/components/molecules/Chip/index.ts
agaein_web/src/components/molecules/Font/Font.style.ts
agaein_web/src/components/molecules/ImageCarousel/ImageCarousel.style.ts
agaein_web/src/components/molecules/ImageCarousel/ImageCarousel.tsx
agaein_web/src/components/molecules/ImageCarousel/index.ts
agaein_web/src/components/molecules/PostItemBox/index.ts
agaein_web/src/components/organism/Comment/Comment.style.ts
agaein_web/src/components/organism/Comment/Comment.tsx
agaein_web/src/components/organism/Comment/CommentItem/CommentItem.style.ts
agaein_web/src/components/organism/Comment/CommentItem/CommentItem.tsx
agaein_web/src/components/organism/Comment/CommentItem/index.ts
agaein_web/src/components/organism/Comment/index.ts
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.style.ts
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/yarn.lock

와이어프레임 기준 게시글 상세화면 레이아웃입니다. 
관련된 컴포넌트들을 추가했습니다.
* feat: Chip, Bookmark 컴포넌트 추가
* feat: Comment 컴포넌트 생성
* feat: Article Detail 추가
* chore: 코드정리, moment 라이브러리 추가
* Image Carousel은 레이아웃만 작성함(추후 작업 예정)

Article Detail페이지 레이아웃 및 관련 컴포넌트 작성

---

agaein_web/homepage.conf

파일 서버 네임 변경

---

agaein_web/src/components/molecules/BookMark/BookMark.style.ts
agaein_web/src/components/molecules/BookMark/BookMark.tsx
agaein_web/src/components/molecules/Button/Button.style.ts
agaein_web/src/components/molecules/Button/index.tsx
agaein_web/src/components/molecules/Chip/Chip.style.ts
agaein_web/src/components/molecules/Font/Font.style.ts
agaein_web/src/components/molecules/Input/index.tsx
agaein_web/src/components/molecules/NavBar/style.tsx
agaein_web/src/components/molecules/PostItemBox/PostItemBox.style.ts
agaein_web/src/components/molecules/PostItemBox/PostItemBox.tsx
agaein_web/src/components/molecules/ReviewItem/ReviewItem.style.ts
agaein_web/src/components/molecules/Textarea/index.tsx
agaein_web/src/components/organism/HomeArticleList/HomeArticleList.style.ts
agaein_web/src/components/organism/HomeArticleList/HomeArticleList.tsx
agaein_web/src/components/organism/HomeHeader/HomeHeader.style.ts
agaein_web/src/components/organism/HomeHeader/HomeHeader.tsx
agaein_web/src/components/organism/createArticle/FormPhoto.tsx
agaein_web/src/components/pages/article/ArticleList.tsx
agaein_web/src/components/pages/createArticle/CreateArticle.style.ts
agaein_web/src/components/pages/createArticle/Step1.tsx
agaein_web/src/hooks/useBookmark.ts
agaein_web/src/theme/style.d.ts
agaein_web/src/theme/theme.ts

* BookMark 컴포넌트 수정
* 하드코딩된 테마 global Theme로 변경
* 커스텀 훅 useBookmark 추가, 북마크 기능 적용 
* PostItem 가져다 쓰는 부분에서는 저 훅 가져다가 북마크 적용하면 됩니다.
* Button 컴포넌트의 width는 padding값으로 제어하는 방식으로 변경했습니다(변경 소요 있음!)

북마크 추가, 글로벌 테마 및 컴포넌트 수정

---

Jenkinsfile

이미지 서버 <-> 우분투 <-> 서버 간의 이미지 파일 바인드마운트 확인
없음

이미지 서버 <-> 우분투 <-> 서버 간의 이미지 파일 바인드마운트 확인

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/resolvers/breed/mutations.ts
agaein_server/graphql/resolvers/user/queries.ts
agaein_server/graphql/typedefs/Article.graphql
agaein_server/graphql/typedefs/index.graphql

* comment, breed, article 부분 delete 기능 구현
* password를 기준으로 비회원 회원 구분 분기문 작성
* password를 기준으로 비회원 회원 구분 분기문 작성했으며, 익명 계정은 user_id는 1로 지정 (kakaoId: "anonymous")

comment, breed, article 부분 delete 기능 구현

---

.github/workflows/agaein.yml

GitHub Actions CI/CD Script 작성 (백엔드)
없음

GitHub Actions CI/CD Script 작성 (백엔드)

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/typedefs/Article.graphql

* 기존 article의 content가 쓸모가 없어져서 삭제, review로 이동
* location 스키마 (lat, lng, address, detail) 4컬럼으로 변경
* lfp foundDate -> lostDate 오타 수정
* feature 부분 해은님이랑 얘기했는데, 생각 좀 해봐야할 듯 합니다. 우리의 주 서비스를 위해서 특징이 서술형이면 어려울 듯해서요.

location, content 스키마 변경

---

agaein_server/graphql/resolvers/article/queries.ts
agaein_web/codegen.yml
agaein_web/src/components/molecules/NavBar/index.tsx
agaein_web/src/components/pages/article/ArticleList.tsx
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/src/components/pages/article/testData.tsx
agaein_web/src/components/pages/createArticle/Step1.tsx
agaein_web/src/components/pages/createArticle/Step3.tsx
agaein_web/src/components/pages/home/Home.tsx
agaein_web/src/contexts/userContext.tsx
agaein_web/src/graphql/queries/Article.fragment.graphql
agaein_web/src/graphql/queries/Article.graphql
agaein_web/src/graphql/queries/Comment.graphql
agaein_web/src/graphql/queries/Global.graphql
agaein_web/src/graphql/queries/User.graphql

바뀐 서버 스키마를 클라이언트에 적용했습니다.
* GraphQL Document 작성(.graphql)
* 이전에 생성되었던 쿼리로 인해 발생하는 클라이언트 오류 해결
* UserContext 수정(쿼리, 쿠키 관련 내용)
* 서버 - type 오류가 있어서 수정했습니다 (type이 boardType이 아니라 Breed type이 내려오고 있었습니다)
* UserContext - 로그아웃 시 에러가 나는데, 이건 추후 수정하겠습니다.

클라이언트에 바뀐 서버 내용 적용

---

agaein_web/src/components/molecules/Button/Button.style.ts
agaein_web/src/components/molecules/Checkbox/index.tsx
agaein_web/src/components/molecules/CustomDatePicker/CustomDatePicker.css
agaein_web/src/components/molecules/CustomDatePicker/CustomDatePicker.tsx
agaein_web/src/components/organism/Form/FormAddress.tsx
agaein_web/src/components/organism/Form/FormAge.tsx
agaein_web/src/components/organism/Form/FormBreed.tsx
agaein_web/src/components/organism/Form/FormCheckbox.tsx
agaein_web/src/components/organism/Form/FormDate.tsx
agaein_web/src/components/organism/Form/FormGender.tsx
agaein_web/src/components/organism/Form/FormGratuity.tsx
agaein_web/src/components/organism/Form/FormName.tsx
agaein_web/src/components/organism/Form/FormPassword.tsx
agaein_web/src/components/organism/Form/FormPhoto.tsx
agaein_web/src/components/organism/Form/index.ts
agaein_web/src/components/pages/createArticle/CreateArticle.style.ts
agaein_web/src/components/pages/createArticle/Step2.tsx
agaein_web/src/theme/style.d.ts
agaein_web/src/theme/theme.ts

- Step2 데이터 정리
- 버튼 컴포넌트 스타일 수정
- Step2 checkbox form 추가
- Step2 스타일 수정
- 실종, 발견 글 분기

Step2 데이터 정리

---

agaein_web/src/graphql/queries/Article.graphql

* createArticle content 이거 하나 안 지워서 다시 올립니다.
없음.

createArticle content 제거

---

agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/resolvers/bookmark/index.ts
agaein_server/graphql/resolvers/bookmark/mutations.ts
agaein_server/graphql/resolvers/bookmark/queries.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/typedefs/Bookmark.graphql
agaein_server/graphql/typedefs/Breed.graphql
agaein_server/graphql/typedefs/index.graphql

* bookmark CRD 작성
* article 한 개받는 쿼리에서 Review 분기가 안 되어 있는 것 추가
* articleDetail의 id가 breedId 받아와지는 버그 수정
bookmark Graphql schema 추가

bookmark CRD 작성 및 articleDetail Review 리팩토링

---

agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/typedefs/comment.graphql
agaein_web/src/graphql/queries/Article.graphql
agaein_web/src/graphql/queries/Comment.graphql

게시글 쿼리 구조를 graphQL에 맞게 변경했습니다. 
측정해보니 성능은 덜 나오지만 몇십 ms 정도 차이가 납니다. 
테스트는 hjinn_query 브랜치에서 해보시면 됩니다. 
큰 변경이니 검토해보시고 변경하거나 유지하도록 합시다.
* resolver chaining을 활용한 쿼리 수정
기본 이론 정리 : [아폴로 서버 독스 번역](https://hjinn.notion.site/Apollo-Server-Resolver-4088b03987d9421dbb5958d06b4f231c)
개선 작업 플로우 정리 : [쿼리 수정 플로우](https://hjinn.notion.site/Graphql-f999012c9d6040878d99640ee533886f)

article 쿼리 구조 개선

---

agaein_server/app.ts

이미지 업로드 크기 및 갯수 변경

---

agaein_server/graphql/typedefs/Breed.graphql

add breed Enum ETC

---

agaein_server/graphql/resolvers/article/mutations.ts

* article password 항상 undefined 되는 것 수정
없음

article password

---

agaein_web/src/components/pages/createArticle/Step2.tsx

임시로 isValid 수정

---

agaein_web/src/components/molecules/CustomDatePicker/CustomDatePicker.style.ts
agaein_web/src/components/molecules/CustomDatePicker/CustomDatePicker.tsx
agaein_web/src/components/molecules/Modal/Modal.style.ts
agaein_web/src/components/molecules/ReviewItem/ReviewItem.style.ts
agaein_web/src/components/molecules/Select/Select.style.ts
agaein_web/src/components/molecules/Select/index.tsx
agaein_web/src/components/organism/Form/FormAddress.tsx
agaein_web/src/components/organism/Form/FormPhoto.tsx
agaein_web/src/components/organism/ReactKakaoMap/ReactKakaoMap.style.ts
agaein_web/src/components/organism/ReactKakaoMap/ReactKakaoMap.tsx
agaein_web/src/components/organism/WitnessModal/WithessReport/WithessReport.style.ts
agaein_web/src/components/organism/WitnessModal/WithessReport/WithessReport.tsx
agaein_web/src/components/organism/WitnessModal/WitnessImageCarousel/WitnessImageCarousel.style.ts
agaein_web/src/components/organism/WitnessModal/WitnessList/WitnessList.style.ts
agaein_web/src/components/organism/WitnessModal/WitnessList/WitnessList.tsx
agaein_web/src/components/organism/WitnessModal/WitnessModal.tsx
agaein_web/src/components/organism/WitnessModal/WitnessModel.style.ts
agaein_web/src/components/pages/createArticle/CreateArticle.style.ts

- theme 색상 일괄 적용
- Address 데이터 변경
- 인라인 style 스타일 컴포넌트화

theme 색상 일괄 적용, Address 데이터 변경

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/typedefs/Article.graphql
agaein_server/index.ts

* email & keyword field 추가
* gender 필드 enum 추가 (male과 female만 가능)
gender 필드 null시 unknown 처리하는 것이 맞나요? 아니면 enum에 unknown을 추가할까요? 프론트에서 어떻게 보내는지 리뷰 남겨주세요.
keyword 보낼 때, 리스트형태로 보내고 받을 때도 리스트형태로 옵니다.
받을 때 예시)
보낼 때 예시)

email & keyword field 추가

---

agaein_web/src/components/molecules/Footer/Footer.style.ts
agaein_web/src/components/molecules/NavBar/NavBar.style.tsx
agaein_web/src/components/organism/AppLayout/AppLayout.style.ts
agaein_web/src/components/organism/AppLayout/AppLayout.tsx
agaein_web/src/components/organism/Form/FormAddress.tsx
agaein_web/src/components/organism/Form/FormAge.tsx
agaein_web/src/components/organism/Form/FormCheckbox.tsx
agaein_web/src/components/organism/Form/FormEmail.tsx
agaein_web/src/components/organism/Form/FormEtc.tsx
agaein_web/src/components/organism/Form/FormGender.tsx
agaein_web/src/components/organism/Form/FormGratuity.tsx
agaein_web/src/components/organism/Form/FormKeyword.tsx
agaein_web/src/components/organism/Form/FormName.tsx
agaein_web/src/components/organism/Form/FormPassword.tsx
agaein_web/src/components/organism/Form/FormPhoto.tsx
agaein_web/src/components/organism/Form/index.ts
agaein_web/src/components/pages/createArticle/Step2.tsx
agaein_web/src/graphql/queries/Article.fragment.graphql

- 레이아웃 수정(최소 높이가 100% 가 되도록, 스크롤이 콘텐츠 안에서 되도록)
- 체크박스 컴포넌트에서 required props 제거
- 키워드, 이메일 폼 추가

Step2 폼 컴포넌트 추가 및 전체 레이아웃 수정

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/resolvers/report/index.ts
agaein_server/graphql/resolvers/report/mutations.ts
agaein_server/graphql/resolvers/report/queries.ts
agaein_server/graphql/typedefs/Report.graphql
agaein_server/graphql/typedefs/index.graphql
agaein_server/index.ts

* 제보 CR 작성(발견리스트)
* image 쿼리개선
* 위의 이미지 받는 부분 쿼리 개선한 부분에 대해서 피드백 부탁드립니다.
그리고 발견제보를 할 때, 지금처럼하면 삭제에 대해서 필요할까요...? 어떤 권한으로 삭제를 진행해야하는지 모르겠어서 한번 논의 해야될 거 같아요. 업데이트도 마찬가지입니다.

제보 CR 작성 & 쿼리 개선

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/resolvers/report/mutations.ts
agaein_server/graphql/typedefs/Report.graphql

* report 스키마 수정 - user, createdAt, updatedAt 추가
* articleId 삭제 롤백

report 스키마 수정 (+ user, createdAt, updatedAt)

---

agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/typedefs/index.graphql

* 게시물 update 기능 추가
* 게시물 생성 시, resolveType으로 articleType을 못 받아와서 에러나는 현상 고침
* Article 생성, 수정 시, resolve의 parent에서 userId를 받아 author를 가져올 수 있도록 변경
없음

게시물 수정 기능 추가 및 게시물 생성 버그 수정

---

agaein_web/src/components/molecules/Pagination/index.tsx
agaein_web/src/components/molecules/PostItemBox/PostItemBox.tsx
agaein_web/src/components/molecules/index.ts
agaein_web/src/components/organism/Comment/Comment.tsx
agaein_web/src/components/organism/Form/FormBreed.tsx
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.style.ts
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/src/components/pages/article/articleList/ArticleList.tsx
agaein_web/src/components/pages/article/articleList/index.ts
agaein_web/src/components/pages/createArticle/Step2.tsx
agaein_web/src/components/pages/createArticle/Step3.tsx
agaein_web/src/graphql/hooks/useArticle.ts
agaein_web/src/graphql/queries/Article.graphql
agaein_web/src/router/index.tsx
agaein_web/src/router/params.ts

게시글 pagination관련 오류 수정했습니다.
useArticle 훅도 추가되었습니다.
* useArticle 추가 (create, delete, update)
* 게시글 pagination 로직 수정 (추후 변경할 생각입니다 - 자세한 설명은 일요일에)
@Haeeeun 님 Step2의 createa쿼리는 useArticle로 옮겼습니다. FormBreed는 안쓰는 import 하나만 삭제한건데 prettier때문에 수정이 많이 일어난 것 처럼 보입니다. 참고해주세요.

pagination 1차 완성 / 코드 리팩토링

---

agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/typedefs/index.graphql

* 각 게시판 타입별 게시물 수 반환 쿼리 작성 (articleLength)
* 없음

articleLength 쿼리 작성

---

agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/typedefs/comment.graphql
agaein_web/src/components/organism/Comment/Comment.style.ts
agaein_web/src/components/organism/Comment/Comment.tsx
agaein_web/src/components/organism/Comment/CommentItem/CommentItem.style.ts
agaein_web/src/components/organism/Comment/CommentItem/CommentItem.tsx
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/src/graphql/apollo.ts
agaein_web/src/graphql/hooks/useComment.ts
agaein_web/src/graphql/queries/Article.fragment.graphql
agaein_web/src/graphql/queries/Comment.graphql
agaein_web/src/utils/typeGuards.ts

대댓글 로직, 댓글 세부기능 추가
대댓글 생성, 댓글 삭제, 수정 등 기능 추가
팝업은 추가하지 않음

댓글 관련 기능 추가 및 수정

---

agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/resolvers/report/mutations.ts
agaein_server/graphql/typedefs/index.graphql

* report delete 작성
* article, comment delete 버그 수정
없음

report delete 작성 및 article, comment delete 버그 수정

---

agaein_web/src/components/molecules/ReviewItem/ReviewItem.style.ts
agaein_web/src/components/molecules/ReviewItem/ReviewItem.tsx
agaein_web/src/components/organism/Form/FormInput.tsx
agaein_web/src/components/organism/Form/FormPhoto.tsx
agaein_web/src/components/organism/Form/FormTextarea.tsx
agaein_web/src/components/organism/WitnessModal/WitnessReport/WitnessReport.tsx
agaein_web/src/components/pages/article/articleList/ArticleList.tsx
agaein_web/src/components/pages/article/articleList/ContentsList.tsx
agaein_web/src/components/pages/createArticle/CreateArticle.style.ts
agaein_web/src/components/pages/createArticle/Step1.tsx
agaein_web/src/components/pages/createArticle/Step2.tsx
agaein_web/src/components/pages/createArticle/Step3.tsx
agaein_web/src/components/pages/review/Review.tsx
agaein_web/src/components/pages/review/ReviewList.tsx
agaein_web/src/components/pages/search/Search.tsx
agaein_web/src/router/index.tsx

- 리뷰 작성 기능 추가
- 홈에서 리스트가 두번 불러와 지는 것, 홈 리스트 전체보기를 눌렀을 경우 캐시 업데이트가 되어 있지 않은 것은 추후 확인 예정입니다

리뷰 작성 기능 추가

---

agaein_web/src/components/organism/WitnessModal/WitnessList/WitnessList.style.ts
agaein_web/src/components/organism/WitnessModal/WitnessList/WitnessList.tsx
agaein_web/src/components/organism/WitnessModal/WitnessModal.tsx
agaein_web/src/components/organism/WitnessModal/WitnessModel.style.ts
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx

report 뮤테이션 캐싱 추가
캐싱 기능은 추가 하면 바로 적용되나
console창에 겂을 못찾는 워닝이 발생합니다..

report 뮤테이션 캐싱 추가

---

agaein_web/src/components/organism/Comment/Comment.tsx
agaein_web/src/graphql/queries/Article.fragment.graphql
agaein_web/src/graphql/queries/Article.graphql
agaein_web/src/graphql/queries/Comment.graphql
agaein_web/src/graphql/queries/report.graphql

코드젠 에러 수정 및 파일이름 변경
코드젠 에러 수정 및 update, delete Report 쿼리 도큐먼트 추가
report.graphql -> Report.graphql

codegen Error 해결

---

agaein_server/common/utils/nickname.ts
agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/typedefs/index.graphql
agaein_web/src/graphql/queries/Article.graphql

* 베스트 후기 쿼리 작성
* 검색쿼리 파라미터만 추가 - 서비스(기능)은 없음
* 랜덤 닉네임 버그 수정
* 베스트 후기 쿼리는 다 만들고 보니, 굳이 만들 필요가 없더라구요. articles 쿼리에서 order을 view로 설정하고 limit를 4로, boardType을 REVIEW로 하면 같은 쿼리가 나옵니다. 일단 만들어 놨는데, 이게 좀 Restful 하네요. 프론트에서 둘 중 하나 원하는 것 써주시고 말씀주시면 베스트 후기 쿼리 삭제하거나 유지하겠습니다! @Haeeeun @hojunin 
* 이미지있는지 없는지에 대해 새로운 컬럼을 만들어서 보내려고 했는데, 지큐엘이라서 articles에서 images를 받을 수 있더라구요. 해당 부분은 images로 이미지가 있는지 없는지를 확인할 수 있을 것 같습니다. @Haeeeun

베스트 후기 및 검색쿼리 파라미터 추가, 랜덤 닉네임 버그 수정

---

agaein_server/graphql/resolvers/article/mutations.ts

* 대댓글 cascade 삭제 대신 content 비우게 변경
* 해당 작업하면서 update 쿼리 리팩토링(article, comment)
* 클라이언트에서는 content가 비었을 경우, 삭제된 걸로 인식하게 바꿔 주어야 합니다.
* 해당 부분 담당하는 분께 언급 부탁드립니다. @hojunin

대댓글 cascade 삭제 대신 content 비우게 변경

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/article/queries.ts
agaein_server/graphql/typedefs/Article.graphql
agaein_web/src/graphql/queries/Article.fragment.graphql

* 검색 쿼리 추가
* Review articleId 추가
* 주인 찾기 / 반려동물 찾기 게시글 찾고 있는 상태 추가(status)
* status는 enum으로 finding과 done만 들어갈 수 있습니다.
* 프론트 codegen 적용 완료

검색 쿼리 & Review articleId 추가 & 게시글 상태 추가

---

agaein_server/graphql/resolvers/user/mutations.ts
agaein_server/graphql/resolvers/user/queries.ts
agaein_server/graphql/typedefs/index.graphql
agaein_server/graphql/typedefs/user.graphql

* 프로필 쿼리 작성
* 유저 업데이트 뮤테이션 작성
* 새로운 타입 및 쿼리 작성으로 프론트 연계 필요.

프로필 쿼리 및 유저 데이터 업데이트 작성

---

agaein_web/src/components/molecules/Select/index.tsx
agaein_web/src/components/organism/Form/FormBreed.tsx
agaein_web/src/components/organism/WitnessModal/WitnessList/WitnessList.style.ts
agaein_web/src/components/organism/WitnessModal/WitnessList/WitnessList.tsx
agaein_web/src/components/organism/WitnessModal/WitnessModal.tsx
agaein_web/src/components/organism/WitnessModal/WitnessModel.style.ts
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.style.ts
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx

Select  공통 컴포넌트화, 발견모달 디자인 수정 및 추가
step2 select만 일단 적용 해놨습니다..!

Select  공통 컴포넌트화, 발견모달 디자인 수정 및 추가

---

agaein_web/package.json
agaein_web/src/assets/styles/GlobalStyle.js
agaein_web/src/assets/styles/slick-theme.css
agaein_web/src/assets/styles/slick.css
agaein_web/src/components/organism/AllReviewList/AllReviewList.tsx
agaein_web/src/components/organism/BestReviewList/BestReviewList.style.ts
agaein_web/src/components/organism/BestReviewList/BestReviewList.tsx
agaein_web/src/components/organism/HomeArticleList/HomeArticleList.style.ts
agaein_web/src/components/organism/HomeArticleList/HomeArticleList.tsx
agaein_web/src/components/organism/ReviewDetail/ReviewDetail.style.ts
agaein_web/src/components/organism/ReviewDetail/index.tsx
agaein_web/src/components/pages/review/ReviewList.style.ts
agaein_web/yarn.lock

- 리뷰 상세 팝업 추가
- 조회수, 리뷰 페이지 셀렉트 컴포넌트 사용은 추후 작업 예정입니다

Add review detail popup

---

agaein_web/src/components/molecules/PostItemBox/PostItemBox.style.ts
agaein_web/src/components/molecules/Select/index.tsx
agaein_web/src/components/pages/crawling/CrawlingResult.style.ts
agaein_web/src/components/pages/crawling/CrawlingResultPage.tsx
agaein_web/src/components/pages/crawling/ResultTable.tsx
agaein_web/src/graphql/queries/Crawling.graphql
agaein_web/src/router/index.tsx

크롤링 결과 페이지 구현
검색페이지 -> 크롤링 결과 페이지 파라미터 JSON String으로 구현 예정

크롤링 결과 페이지 구현

---

agaein_server/graphql/resolvers/crawling/mutations.ts
agaein_server/graphql/resolvers/crawling/queries.ts
agaein_server/graphql/typedefs/Crawling.graphql
agaein_server/graphql/typedefs/index.graphql

일요일에 회의했던 내용을 바탕으로 query문과 mutation문을 분리하였습니다.
나중에 크롤링했던 기록을 볼 수 있도록 CrawlingHistory 쿼리를 추가하였습니다.
keywords 쿼리 에러 고쳤습니다.
없음. @Ting97ok 머지되면 이거 쓰면댕~ @hojunin 리뷰 부탁쓰!

feat: 🎸 crawling dummy api

---

agaein_web/src/components/pages/crawling/CrawlingResultPage.tsx
agaein_web/src/components/pages/crawling/ResultTable.tsx
agaein_web/src/components/pages/search/Search.tsx
agaein_web/src/graphql/queries/Crawling.graphql
agaein_web/src/router/index.tsx
agaein_web/src/router/params.ts

- 크롤링 페이지 뮤테이션 -> 쿼리 변경
- 검색 페이지 변경

update 검색, 크롤링 페이지

---

agaein_crawling_server/database/models.py
agaein_crawling_server/sites/angel.py
agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/crawling/mutations.ts
agaein_server/graphql/resolvers/crawling/queries.ts
agaein_server/graphql/typedefs/Crawling.graphql
agaein_server/graphql/typedefs/index.graphql
agaein_server/index.ts
agaein_web/src/components/pages/search/Search.tsx
agaein_web/src/graphql/queries/Crawling.graphql

크롤링 요청하면 진짜 데이터 나오게 변경.
프론트와 데이터를 좀 맞춰봐야할 것 같습니다. - QA때 한꺼번에 하는게 나을려나? 모여서 하루만에 뚝딱하게끔? 
@hojunin @Haeeeun @Ting97ok

feat: 🎸 crawling real data

---

agaein_web/src/components/molecules/Button/Button.style.ts
agaein_web/src/components/molecules/NavBar/NavBar.style.tsx
agaein_web/src/components/molecules/NavBar/NavBar.tsx
agaein_web/src/components/molecules/PostItemBox/PostItemBox.style.ts
agaein_web/src/components/organism/AllReviewList/AllReviewList.tsx
agaein_web/src/components/organism/AppLayout/AppLayout.style.ts
agaein_web/src/components/organism/AppLayout/AppLayout.tsx
agaein_web/src/components/organism/BestReviewList/BestReviewList.tsx
agaein_web/src/components/organism/ReviewDetail/index.tsx
agaein_web/src/components/pages/createArticle/CreateArticle.style.ts
agaein_web/src/components/pages/myPage/MyPage.tsx
agaein_web/src/components/pages/search/Search.tsx
agaein_web/src/index.css
agaein_web/src/router/index.tsx

- 헤더 드랍박스 추가
- 마이페이지 라우터 추가
- 리뷰 조회수 캐시 수정
- app layout 수정
- post item height 수정
- 토글버튼 추가 (대현이가 마무리 작업 ★)

리뷰 조회수 수정 및 리팩토링

---

agaein_crawling_server/sites/angel.py
agaein_crawling_server/sites/common/kakaomap.py
agaein_server/graphql/resolvers/crawling/mutations.ts
agaein_server/graphql/resolvers/crawling/queries.ts

저번 회의에서 말한대로 크롤링에 점수 추가했습니다.
history 데이터 초기화되었습니다. (@Ting97ok ) 새로 입력해주세요.
@hojunin 리뷰부탁쓰~~

feat: 🎸 add crawling breed, location score

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/resolvers/user/mutations.ts
agaein_server/graphql/typedefs/User.graphql
agaein_server/graphql/typedefs/index.graphql
agaein_web/src/graphql/queries/User.graphql

유저 프로필 이미지 추가(User type & mutation updateProfile)
웹의 타입도 변경완료.

유저 프로필 이미지 기능 추가

---

agaein_web/src/components/organism/MyArticles/index.tsx
agaein_web/src/components/organism/MyBookmarkList/index.tsx
agaein_web/src/components/organism/MyInfo/index.tsx
agaein_web/src/components/pages/myPage/MyPage.style.ts
agaein_web/src/components/pages/myPage/MyPage.tsx

- 마이페이지 마크업
http://localhost:3000/myPage
- 서버 연동 추후 작업 예정

마이페이지 마크업 작업

---

agaein_web/src/components/pages/crawling/CrawlingResult.style.ts
agaein_web/src/components/pages/crawling/CrawlingResultPage.tsx
agaein_web/src/components/pages/crawling/ResultTable.tsx
agaein_web/src/components/pages/createArticle/CreateArticle.style.ts
agaein_web/src/components/pages/search/Search.tsx
agaein_web/src/graphql/apollo.ts
agaein_web/src/utils/converter.ts

크롤링 결과 페이징, 필터 작업

---

agaein_web/package.json
agaein_web/src/components/pages/common/Error/Error.tsx
agaein_web/src/graphql/apollo.ts
agaein_web/src/hooks/useBookmark.ts
agaein_web/src/index.js
agaein_web/src/router/index.tsx
agaein_web/yarn.lock

* Error Boundary 추가
* 리액트 특성 상 Error Boundary는 로컬에서 테스트가 불가능하여 테스트를 위해 production에 올립니다!
* 에러 페이지는 디자인 나오는대로 반영 예정!
* 실행 시 **패키지 설치** 해야함 (yarn)

Error Boundary 추가

---

agaein_web/src/utils/converter.ts

chore: convertor.ts - 임시코드 제거

---

agaein_server/graphql/resolvers/user/queries.ts
agaein_server/graphql/typedefs/Comment.graphql
agaein_server/graphql/typedefs/User.graphql

feat: 🎸 profile comment

---

agaein_web/package.json
agaein_web/src/contexts/userContext.tsx
agaein_web/src/graphql/apollo.ts
agaein_web/src/graphql/queries/User.graphql
agaein_web/src/index.js
agaein_web/yarn.lock

* env 파일 추가
* 로그인 mutation 수정
.evn 추가

Login Mutation 수정 및 .env 추가

---

agaein_server/codegen.yml
agaein_server/common/auth/jwtToken.ts
agaein_server/dockerfile
agaein_server/graphql/customTypes.ts
agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/resolvers/article/services.ts
agaein_server/graphql/resolvers/bookmark/services.ts
agaein_server/graphql/resolvers/breed/mutations.ts
agaein_server/graphql/resolvers/breed/queries.ts
agaein_server/graphql/resolvers/breed/services.ts
agaein_server/graphql/resolvers/report/mutations.ts
agaein_server/graphql/resolvers/report/queries.ts
agaein_server/graphql/resolvers/report/services.ts
agaein_server/graphql/resolvers/user/mutations.ts
agaein_server/graphql/resolvers/user/queries.ts
agaein_server/graphql/resolvers/user/services.ts
agaein_server/graphql/typedefs/Breed.graphql
agaein_server/graphql/types.ts
agaein_server/package.json
agaein_server/yarn.lock

- Breed Enum의 ETC 삭제
- codegen 적용
-  breed, user, report Domain refactoring
- codegen 부분은 도커 파일에 명령어를 추가했고, 서버에 올릴 때 확인이 필요합니다.

Breed, User, Report 도메인 리팩토링 및 codegen  적용

---

agaein_server/graphql/database.ts
agaein_server/graphql/resolvers/bookmark/mutations.ts
agaein_server/graphql/resolvers/bookmark/queries.ts
agaein_server/graphql/resolvers/bookmark/services.ts
agaein_server/graphql/resolvers/breed/queries.ts
agaein_server/graphql/resolvers/breed/services.ts
agaein_server/graphql/resolvers/crawling/mutations.ts
agaein_server/graphql/resolvers/crawling/queries.ts
agaein_server/graphql/resolvers/crawling/services.ts
agaein_server/graphql/resolvers/user/queries.ts
agaein_server/graphql/typedefs/Crawling.graphql
agaein_server/graphql/typedefs/index.graphql
agaein_server/graphql/types.ts

Crawling & Bookmark domain Refactoring
테이블이 잘못 만들어진게 하나 있어서 변경했습니다. 
크롤링 히스토리 테이블에 user랑 연관지어야할 외래 키를 breed랑 연관 지었었네요;;;
그리고 크롤링에 필수적으로 들어가야할 데이터들이 필수로 되어 있지 않아서 타입에 필수타입으로 변경하였습니다.

Crawling & Bookmark domain Refactoring

---

agaein_web/src/components/molecules/NavBar/NavBar.style.tsx
agaein_web/src/components/molecules/NavBar/NavBar.tsx
agaein_web/src/components/organism/Comment/CommentItem/CommentItem.tsx
agaein_web/src/components/organism/Form/FormKeyword.tsx
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/src/contexts/userContext.tsx

- 카카오 로그인 버튼이 잠깐 보이는 버그 수정
- 키워드 추가 버튼 disabled 조건 추가
- 네비바-헤더 z-index 조정
- 답글의 답글 기능 막기
- 게시글 상세 - 나이 표기법 변경
- 게시글 상세 - 컨텐츠 없을 때 NotFound 컴포넌트 로드

t # 커밋 6개가 섞인 결과입니다.

---

agaein_web/src/components/molecules/Chip/Chip.tsx
agaein_web/src/components/molecules/CustomDatePicker/CustomDatePicker.tsx
agaein_web/src/components/molecules/SearchBar/SearchBar.style.ts
agaein_web/src/components/molecules/SearchBar/index.tsx
agaein_web/src/components/molecules/Select/index.tsx
agaein_web/src/components/organism/AllReviewList/AllReviewList.tsx
agaein_web/src/components/organism/Comment/Comment.tsx
agaein_web/src/components/organism/Comment/CommentInput/CommentInput.tsx
agaein_web/src/components/organism/Form/FormAddress.tsx
agaein_web/src/components/organism/Form/FormBreed.tsx
agaein_web/src/components/organism/Form/FormDate.tsx
agaein_web/src/components/organism/Form/FormKeyword.tsx
agaein_web/src/components/organism/MyBookmarkList/index.tsx
agaein_web/src/contexts/bookmarkContext.tsx
agaein_web/src/contexts/userContext.tsx

Lint 오류 수정

---

agaein_web/src/components/organism/MyArticles/index.tsx
agaein_web/src/components/organism/MyBookmarkList/index.tsx
agaein_web/src/components/organism/MyInfo/index.tsx
agaein_web/src/components/pages/myPage/MyPage.style.ts
agaein_web/src/components/pages/myPage/MyPage.tsx
agaein_web/src/graphql/queries/User.fragment.graphql
agaein_web/src/graphql/queries/User.graphql

내 정보 수정 기능 추가

---

agaein_web/src/components/pages/createArticle/Step2.tsx
agaein_web/src/contexts/userContext.tsx

로그인 성공하면 fetchMe 함수로 유저 데이터 업데이트

최초 로그인 시 유저데이터 변경 오류 수정

---

agaein_web/src/components/molecules/Chip/Chip.style.ts
agaein_web/src/components/molecules/Chip/Chip.tsx
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/src/contexts/userContext.tsx
agaein_web/src/graphql/apollo.ts
agaein_web/src/graphql/hooks/useArticle.ts
agaein_web/src/graphql/queries/Article.graphql
agaein_web/src/utils/converter.ts

- 게시글 작성자가 게시글 상세에서 찾기완료 버튼을 눌렀을 때 게시글 상태 변경하도록 기능 추가
- @Haeeeun 마이페이지에서 찾기 완료 처리 할 때 `useArticle.ts`의 `updateArticleStatus` 훅 사용하면 됩니다~

찾기 완료 기능 추가

---

agaein_server/jest.config.ts
agaein_server/package.json
agaein_server/tests/article.test.ts
agaein_server/tests/bookmark.test.ts
agaein_server/tests/breed.test.ts
agaein_server/tests/crawling.test.ts
agaein_server/tests/index.test.ts
agaein_server/tests/reports.test.ts
agaein_server/tests/user.test.ts
agaein_server/yarn.lock

어거지로 30% TestCode 만들었습니다.
코드는 이렇게 만들면 안 됩니다.

server TestCode 추가

---

agaein_server/common/utils/email.ts
agaein_server/graphql/resolvers/contact/index.ts
agaein_server/graphql/resolvers/contact/mutations.ts
agaein_server/graphql/resolvers/contact/services.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/typedefs/index.graphql
agaein_server/graphql/types.ts
agaein_server/jest.config.ts
agaein_server/package.json
agaein_server/tests/article.test.ts
agaein_server/tests/bookmark.test.ts
agaein_server/tests/breed.test.ts
agaein_server/tests/crawling.test.ts
agaein_server/tests/index.test.ts
agaein_server/tests/reports.test.ts
agaein_server/tests/user.test.ts
agaein_server/yarn.lock

Email 문의하기 api 추가

---

agaein_web/src/components/molecules/Footer/CustomerServiceContents.tsx
agaein_web/src/components/molecules/Footer/Footer.tsx
agaein_web/src/graphql/queries/Global.graphql

feat: 문의하기 기능 추가

---

agaein_server/graphql/customTypes.ts
agaein_server/graphql/resolvers/index.ts
agaein_server/graphql/typedefs/Report.graphql
agaein_server/graphql/typedefs/User.graphql
agaein_server/graphql/types.ts

profile 쿼리에 profileReport 타입 추가
report 보는 곳에 article 데이터가 필요해서 이렇게 변경됨.

fix: profile 쿼리에 profileReport 타입 추가

---

agaein_server/common/auth/jwtToken.ts
agaein_server/graphql/resolvers/article/mutationServices.ts
agaein_server/graphql/resolvers/article/mutations.ts
agaein_server/graphql/resolvers/article/queryServices.ts

refactor: article paging keyword error fix & comment refactoring

---

agaein_server/yarn.lock
agaein_web/src/components/organism/BestReviewList/BestReviewList.tsx
agaein_web/src/components/organism/Form/FormBreed.tsx
agaein_web/src/components/organism/ReviewDetail/index.tsx
agaein_web/src/components/organism/WitnessModal/WitnessModal.tsx
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/src/components/pages/crawling/CrawlingResultPage.tsx
agaein_web/src/components/pages/createArticle/Step1ButtonImage.tsx
agaein_web/src/components/pages/home/Home.tsx
agaein_web/src/contexts/bookmarkContext.tsx
agaein_web/src/contexts/userContext.tsx
agaein_web/src/graphql/apollo.ts
agaein_web/src/graphql/hooks/useArticle.ts
agaein_web/src/index.css

- 캐시로 조회수 올리는 로직 제거
- 게시글 가져오는 쿼리 -> fetchPolicy 변경
- 로그아웃 후 storeReset 코드 제거 -> 이로인해 토큰을 요하는 쿼리들이 리페칭되고 있어서 먹통이 되는 것이었음.
- 게시글 상세 진입 시 scroll to top 추가
- 리뷰 상세 볼 때 review.articleDetail.id값이 아니라 review.id 혹은 review.articleDetail.articleId가 맞는 것 같은데 동작은 잘되는게 이상합니다 -> 일요일에 같이 봅시다요

feat: 조회수 버그, 로그아웃 이후 먹통되는 버그 수정

---

agaein_web/package.json
agaein_web/src/components/molecules/PostItemBox/PostItemBox.style.ts
agaein_web/src/components/organism/MyArticles/ArticlesTable.tsx
agaein_web/src/components/organism/MyArticles/index.tsx
agaein_web/src/components/organism/MyArticles/type.ts
agaein_web/src/components/organism/MyBookmarkList/index.tsx
agaein_web/src/components/organism/MyInfo/index.tsx
agaein_web/src/components/pages/myPage/MyPage.style.ts
agaein_web/src/components/pages/myPage/MyPage.tsx
agaein_web/src/graphql/queries/User.fragment.graphql
agaein_web/src/graphql/queries/User.graphql
agaein_web/yarn.lock

- react error overlay 추가: 페이지 에러시 프레임 뜨는 문제 수정
- 홈페이지 태그 줄넘김 되지 않도록 수정
- 마이페이지 기능 구현
- 내 정보도 profile 데이터로 변경
- 내 발견내역
- 후기 작성 이동

Implement mypage

---

agaein_server/graphql/resolvers/bookmark/mutations.ts
agaein_server/graphql/resolvers/report/services.ts
agaein_server/tests/article.test.ts
agaein_server/tests/bookmark.test.ts
agaein_server/tests/breed.test.ts
agaein_server/tests/reports.test.ts

refactor: testCode 통합 및 리팩토링

---

agaein_web/src/components/organism/AllReviewList/AllReviewList.tsx
agaein_web/src/components/organism/BestReviewList/BestReviewList.tsx
agaein_web/src/components/organism/HomeArticleList/HomeArticleList.tsx
agaein_web/src/components/pages/article/articleList/ContentsList.tsx
agaein_web/src/contexts/bookmarkContext.tsx
agaein_web/src/contexts/userContext.tsx
agaein_web/src/graphql/queries/Article.graphql
agaein_web/src/graphql/queries/Bookmark.graphql
agaein_web/src/utils/typeGuards.ts

- articles 쿼리 변경사항 클라이언트 동기화
- deleteBookmark 뮤테이션 변경사항 클라이언트 동기화
- 아직 페이지네이션 구현은 하지 않았음!

feat: 페이지네이션 쿼리 / 북마크 삭제 쿼리 적용

---

agaein_crawling_server/main.py
agaein_crawling_server/sites/animal.py

새로운 크롤링 사이트 사전작업
필요한 해당 사이트 인덱스 구하는 코드 작업 및 DB 저장

새 크롤링 사이트 추가

---

agaein_web/package.json
agaein_web/src/components/pages/common/Error/ErrorBoundary.tsx
agaein_web/src/index.tsx
agaein_web/yarn.lock

feat: 에러바운더리 수정

---

agaein_crawling_server/database/models.py
agaein_crawling_server/main.py
agaein_crawling_server/sites/agaein.py
agaein_crawling_server/sites/angel.py
agaein_crawling_server/sites/animal.py
agaein_crawling_server/sites/common/counting.py

agaein site Crawling 및 당일 크롤링 총 개수 저장
크롤링 작업 완료입니다. 총 3개 사이트
https://www.animal.go.kr
http://www.angel.or.kr
https://www.agaein.com
agaein 사이트는 데이터 정리되는대로 주석 풀겠습니다~

agaein site Crawling 및 당일 크롤링 총 개수 저장

---

agaein_web/src/components/molecules/Footer/Footer.tsx
agaein_web/src/components/organism/Billboard/Billboard.style.ts
agaein_web/src/components/organism/Billboard/Billboard.tsx
agaein_web/src/components/organism/Billboard/BillboardSection/BillboardSection.style.ts
agaein_web/src/components/organism/Billboard/BillboardSection/BillboardSection.tsx
agaein_web/src/components/organism/Billboard/index.tsx
agaein_web/src/components/pages/home/Home.tsx
agaein_web/src/graphql/queries/Crawling.graphql

feat: 전광판 기능 추가

---

agaein_web/src/components/molecules/Footer/Footer.tsx
agaein_web/src/components/organism/Billboard/BillboardSection/BillboardSection.tsx

feat: 오타 수정(Footer, Billboard)

---

agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx
agaein_web/src/components/pages/crawling/ResultTable.tsx
agaein_web/src/graphql/apollo.ts

- 크롤링 결과화면 : 키 주입 / 품종 및 성별 데이터 변환

feat: 크롤링 결과화면 수정

---

agaein_web/src/components/organism/MyArticles/ArticlesTable.tsx
agaein_web/src/components/organism/MyArticles/type.ts
agaein_web/src/components/organism/MyBookmarkList/index.tsx
agaein_web/src/components/pages/myPage/MyPage.style.ts
agaein_web/src/graphql/queries/User.fragment.graphql
agaein_web/src/router/index.tsx

- 마이페이지 내 발견 내역 리스트 데이터 연동
- @tagrn 아티클 코멘트 개수도 보내주실 수 있나여?
- 후기작성이 articleId 와 연결되어 있지 않음

Add report list data on my page

---

agaein_web/src/components/molecules/ImageCarousel/ImageCarousel.style.ts
agaein_web/src/components/molecules/PostItemBox/PostItemBox.tsx
agaein_web/src/components/molecules/ReviewItem/ReviewItem.tsx
agaein_web/src/components/organism/ReviewDetail/index.tsx
agaein_web/src/components/pages/article/articleDetail/ArticleDetail.tsx

fix: qa 적용

---

agaein_web/src/components/pages/common/Loading/Loading.style.ts

fix : 로딩 컴포넌트에 배경색 부여
